# Cantor "compose mode" Russian — host-side support, as a home-manager module.
#
# Pairs with the keyboard firmware (modules/shofel/unicode_ru): the Cantor emits
# each Cyrillic / symbol glyph as `Compose + <code>`, where Compose is Scroll
# Lock. This module wires the host to interpret that stream:
#   - ~/.XCompose      : the Compose -> glyph table (generated, committed here)
#   - xkb compose:sclk : Scroll Lock = Compose (Multi_key)
#
# Import from your dotfiles flake via a `flake = false` input:
#
#   # flake.nix inputs:
#   cantor-kb = { url = "github:shofel/keyboards"; flake = false; };
#   # (local iteration: url = "git+file:///path/to/your/keyboards/checkout";)
#
#   # home-manager module:
#   imports = [ "${inputs.cantor-kb}/nix/cantor-compose-ru.nix" ];
#   cantor.composeRu = {
#     enable = true;
#     baseXkbOptions = [ "terminate:ctrl_alt_bksp" "lv3:ralt_switch" ];
#   };
{ config, lib, ... }:
let
  cfg = config.cantor.composeRu;
in {
  options.cantor.composeRu = {
    enable = lib.mkEnableOption "Cantor compose-mode Russian host support";

    baseXkbOptions = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "terminate:ctrl_alt_bksp" "lv3:ralt_switch" ];
      description = ''
        Your other GNOME xkb options. `compose:sclk` is appended and this module
        becomes the sole writer of
        `org/gnome/desktop/input-sources` `xkb-options`, so list every option you
        want kept here.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Compose -> Cyrillic/symbol table (generated by tools/gen_unicode_compose.py).
    home.file.".XCompose".source = ../tools/XCompose.generated;

    # Scroll Lock -> Compose (Multi_key), preserving the caller's other options.
    dconf.settings."org/gnome/desktop/input-sources".xkb-options =
      cfg.baseXkbOptions ++ [ "compose:sclk" ];
  };
}
