#!/usr/bin/env python3
"""
Single source of truth for Cantor "compose mode" unicode emission.

Despite the ru_* naming, this covers every glyph the Cantor emits via Compose,
not just Russian: Cyrillic, typographic symbols (« » — № §), currency (₺ ₽ €),
and emoji (flowers + reactions).

Emits, from one table:
  --table     <path>  C array `ru_compose_code[]` indexed by `enum unicode_names`
                      (include from the unicode_ru module).
  --xcompose  <path>  ~/.XCompose block mapping each Compose sequence -> glyph.
  --cheatsheet<path>  human-readable glyph -> sequence reference.

Scheme (collision-free private prefixes; every sequence is exactly 3 keys):
  Compose(=Scroll Lock via xkb compose:sclk) + prefix + selector
    prefix 'q'  -> lowercase Cyrillic / typographic symbols (« » via q[ q])
    prefix 'Q'  -> uppercase Cyrillic   (Shift+q -> keysym Q)
    prefix '$'  -> currency (₺ ₽ €), self-documenting money prefix
    prefix '%'  -> emoji (flowers + reactions), zero-collision private prefix.
                  ('@' was avoided: Telegram Desktop treats a bare '@' as a
                  mention trigger, leaving a stale preedit '@' beside the glyph.)
  No sequence is a prefix of another, and the private prefixes do not collide
  with the included system table.
"""
import argparse

# Cyrillic letters in the SAME order as `enum unicode_names` in
# modules/shofel/unicode_ru/introspection.h. (enum_suffix, lower_cp, upper_cp)
LETTERS = [
    ("A",    0x430, 0x410), ("B",    0x431, 0x411), ("V",    0x432, 0x412),
    ("G",    0x433, 0x413), ("D",    0x434, 0x414), ("E",    0x435, 0x415),
    ("YO",   0x451, 0x401), ("ZH",   0x436, 0x416), ("Z",    0x437, 0x417),
    ("I",    0x438, 0x418), ("Y",    0x439, 0x419), ("K",    0x43A, 0x41A),
    ("L",    0x43B, 0x41B), ("M",    0x43C, 0x41C), ("N",    0x43D, 0x41D),
    ("O",    0x43E, 0x41E), ("P",    0x43F, 0x41F), ("R",    0x440, 0x420),
    ("S",    0x441, 0x421), ("T",    0x442, 0x422), ("U",    0x443, 0x423),
    ("F",    0x444, 0x424), ("H",    0x445, 0x425), ("TS",   0x446, 0x426),
    ("CH",   0x447, 0x427), ("SH",   0x448, 0x428), ("SHCH", 0x449, 0x429),
    ("YERU", 0x44B, 0x42B), ("SOFT", 0x44C, 0x42C), ("HARD", 0x44A, 0x42A),
    ("EE",   0x44D, 0x42D), ("YU",   0x44E, 0x42E), ("YA",   0x44F, 0x42F),
]

# Typographic symbols already on the SYM layer (enum_name, cp, selector char).
SYMBOLS = [
    ("U_MDASH",   0x2014, "7"),   # —
    ("U_NUMERO",  0x2116, "8"),   # №
    ("U_SECTION", 0x00A7, "9"),   # §
]

# Standalone glyphs emitted by dedicated keycodes (KK_LANGLE/KK_RANGLE), NOT via
# unicode_map — so they get an XCompose entry + cheatsheet line but no C-table
# row (the keymap hardcodes their codes). (cp, selector char, glyph)
EXTRA = [
    (0x00AB, "[", "«"),
    (0x00BB, "]", "»"),
]

# Currency signs — emitted by leader seqs (leader,m,<l|r|e>) via
# ru_compose_emit_code. Standalone glyphs under a private '$' prefix
# (self-documenting: $ = money). Like EXTRA: XCompose + cheatsheet, no C-table row.
CURRENCY = [
    (0x20BA, "l", "₺"),  # Turkish lira (leader,m,l — TRY)
    (0x20BD, "r", "₽"),  # ruble        (leader,m,r — RUB)
    (0x20AC, "e", "€"),  # euro         (leader,m,e — EUR)
]

# Emoji — emitted by leader seqs (leader,{a|i},<sel>) via ru_compose_emit_code.
# Standalone glyphs under a private '%' prefix (zero-collision, chosen like '$').
# NOT '@': Telegram Desktop intercepts a bare '@' for its mention autocomplete,
# so composing '@t' left a stale preedit '@' next to the 🌷 (see keymap.c).
# Like EXTRA/CURRENCY: XCompose + cheatsheet, no C-table row.
# (cp, selector, glyph, mnemonic) — the selector char appears in the mnemonic,
# and the generated reference bolds it (its first occurrence).
EMOJI = [
    (0x1F337, "t", "🌷", "tulip"),
    (0x1F339, "r", "🌹", "rose"),
    (0x1F338, "c", "🌸", "cherry"),
    (0x1F33A, "h", "🌺", "hibiscus"),
    (0x1F33B, "s", "🌻", "sunflower"),
    (0x1F33C, "d", "🌼", "daisy"),
    (0x1F44D, "u", "👍", "thumbup"),
    (0x1F44C, "o", "👌", "ok"),
    (0x1F914, "k", "🤔", "think"),
    (0x1F9D0, "m", "🧐", "monocle"),
    (0x1F91D, "n", "🤝", "handshake"),
]

# Keysym names for selector chars whose keysym name isn't the char itself.
KEYSYM = {"[": "bracketleft", "]": "bracketright", "$": "dollar", "%": "percent"}
def keysym(ch):
    return KEYSYM.get(ch, ch)

# 33 selectors: a..z then 0..6
SELECTORS = [chr(ord("a") + i) for i in range(26)] + [str(i) for i in range(7)]
assert len(SELECTORS) >= len(LETTERS)


def rows():
    """Yield (c_index, code, keysyms, glyph, cp) for every compose entry."""
    for (suf, lc, uc), sel in zip(LETTERS, SELECTORS):
        yield (f"RU_LC_{suf}", "q" + sel, ("q", sel), chr(lc), lc)
        yield (f"RU_UC_{suf}", "Q" + sel, ("Q", sel), chr(uc), uc)
    for name, cp, sel in SYMBOLS:
        yield (name, "q" + sel, ("q", sel), chr(cp), cp)


def gen_table():
    out = [
        "// GENERATED by tools/gen_unicode_compose.py — do not edit by hand.",
        "// Compose-sequence selector per `enum unicode_names`. NULL = sent raw.",
        "static const char *const ru_compose_code[] = {",
    ]
    for cidx, code, _ks, glyph, _cp in rows():
        out.append(f'    [{cidx}] = "{code}",  // {glyph}')
    out.append("};")
    return "\n".join(out) + "\n"


def gen_xcompose():
    out = [
        "# GENERATED by tools/gen_unicode_compose.py — do not edit by hand.",
        "# Cantor compose-mode Russian. Compose = Scroll Lock (xkb compose:sclk).",
        'include "%L"',
        "",
    ]
    for _cidx, _code, (p, s), glyph, cp in rows():
        out.append(f'<Multi_key> <{keysym(p)}> <{keysym(s)}> : "{glyph}" U{cp:04X}')
    for cp, s, glyph in EXTRA:
        out.append(f'<Multi_key> <q> <{keysym(s)}> : "{glyph}" U{cp:04X}')
    for cp, s, glyph in CURRENCY:
        out.append(f'<Multi_key> <dollar> <{keysym(s)}> : "{glyph}" U{cp:04X}')
    for cp, s, glyph, _word in EMOJI:
        out.append(f'<Multi_key> <{keysym("%")}> <{keysym(s)}> : "{glyph}" U{cp:04X}')
    return "\n".join(out) + "\n"


def gen_cheatsheet():
    out = ["Cantor compose-mode Russian — Compose is Scroll Lock.", ""]
    for _cidx, code, _ks, glyph, cp in rows():
        out.append(f"  {glyph}  U+{cp:04X}   Compose {' '.join(code)}")
    for cp, s, glyph in EXTRA:
        out.append(f"  {glyph}  U+{cp:04X}   Compose q {s}")
    for cp, s, glyph in CURRENCY:
        out.append(f"  {glyph}  U+{cp:04X}   Compose $ {s}")
    for cp, s, glyph, _word in EMOJI:
        out.append(f"  {glyph}  U+{cp:04X}   Compose % {s}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--table")
    ap.add_argument("--xcompose")
    ap.add_argument("--cheatsheet")
    a = ap.parse_args()
    work = {a.table: gen_table, a.xcompose: gen_xcompose, a.cheatsheet: gen_cheatsheet}
    for path, fn in work.items():
        if path:
            with open(path, "w", encoding="utf-8") as f:
                f.write(fn())
            print(f"wrote {path}")
    if not any(work):
        print(gen_table()); print(gen_xcompose()); print(gen_cheatsheet())


if __name__ == "__main__":
    main()
