#!/usr/bin/env python3
"""Off-target tests for gen_layer_schemes.py (layer-scheme generator)."""
import sys, os, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_layer_schemes as g

# 42 tokens: rows of 12/12/12 + 6 thumbs. Paren-nested token included on purpose.
TOKENS = (
    ["KC_Q"] * 11 + ["LT(L_SYMBOLS, KC_ENTER)"]
    + ["KC_A"] * 12
    + ["KC_Z"] * 12
    + ["KC_SPACE"] * 6
)

SNIPPET = (
    "enum my_layer_names {\n  L_ONE,\n  L_TWO,\n};\n"
    "const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {\n"
    "  [L_ONE] = LAYOUT_split_3x6_3(/* old scheme\n   q q q */\n    "
    + ", ".join(TOKENS)
    + "\n  ),\n"
    "  [L_TWO] = LAYOUT_split_3x6_3( // line comment\n    "
    + ", ".join(TOKENS)
    + "\n  ),\n"
    "};\n"
)

def test_layer_names():
    assert g.layer_names(SNIPPET) == ["L_ONE", "L_TWO"]

def test_extract_layers():
    layers = g.extract_layers(SNIPPET)
    assert [name for name, _ in layers] == ["L_ONE", "L_TWO"]
    for _, toks in layers:
        assert len(toks) == 42
        assert toks[11] == "LT(L_SYMBOLS, KC_ENTER)"  # comma inside parens kept
        assert toks[0] == "KC_Q" and toks[41] == "KC_SPACE"

def test_wrong_token_count_fatal():
    bad = SNIPPET.replace(", ".join(TOKENS), ", ".join(TOKENS[:41]), 1)
    try:
        g.extract_layers(bad)
    except SystemExit:
        pass
    else:
        raise AssertionError("41 tokens should be fatal")

def test_glyph_rules():
    assert g.glyph("KC_A") == "a"
    assert g.glyph("KC_7") == "7"
    assert g.glyph("KC_F12") == "F12"
    assert g.glyph("RU_YO") == "ё"
    assert g.glyph("__") == "__"
    assert g.glyph("XX") == "·"
    assert g.glyph("KC_BSPC") == "⌫"
    assert g.glyph("LT(L_SYMBOLS, KC_ENTER)") == "ret"

def test_unknown_keycode_fatal():
    try:
        g.glyph("KC_TOTALLY_NEW")
    except SystemExit:
        pass
    else:
        raise AssertionError("unknown keycode should be fatal")

def test_real_keymap_fully_covered():
    src = g.KEYMAP.read_text(encoding="utf-8")
    layers = g.extract_layers(src)
    assert len(layers) == 7
    for name, toks in layers:
        for t in toks:
            g.glyph(t)  # SystemExit here = missing glyph for a real keycode

def test_render_grid_golden():
    toks = (
        ["KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Y"] + ["KC_U", "KC_I", "KC_O", "KC_P", "KC_A", "KC_S"]
        + ["XX", "KC_PGUP", "KC_D", "KC_F", "KC_G", "KC_H"] + ["KC_J", "KC_K", "KC_L", "KC_Z", "KC_X", "KC_C"]
        + ["__"] * 12
        + ["QK_LEAD", "KK_SHIFT", "KK_SYMBO", "KK_RET", "KC_SPACE", "QK_LEAD"]
    )
    # Golden derived from the renderer rules: per-column width = widest glyph
    # in that column over the 3 main rows ([2,3,2,2,...] here), cells joined by
    # 2 spaces, padded halves joined by 8 spaces, trailing whitespace stripped,
    # left thumb cluster right-aligned to the left half's end.
    expected = "\n".join([
        "q   w    e   r   t   y         u   i   o   p   a   s",
        "·   pg↑  d   f   g   h         j   k   l   z   x   c",
        "__  __   __  __  __  __        __  __  __  __  __  __",
        "         LEAD  sft  SYM        ret  spc  LEAD",
    ])
    assert g.render_grid(toks) == expected

def test_doc_paragraph():
    src = (
        "/**\n * Mouse layer — POLAR mode.\n *\n * More prose that is NOT the first paragraph.\n */\n"
        "  [L_ONE] = LAYOUT_split_3x6_3(\n    " + ", ".join(TOKENS) + "\n  ),"
    )
    assert g.doc_paragraph(src, "L_ONE") == "Mouse layer — POLAR mode."

def test_gen_doc_contains_all_layers():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    for title in ["Base (BOO)", "Russian", "Symbols", "Numbers & Navigation",
                  "F-keys & System", "Mouse — Polar", "Mouse — Bisect"]:
        assert f"## {title}" in doc
    # friendly titles replace raw enum headings, but the enum survives in <sub>
    assert "## L_NUM_NAV" not in doc
    assert "`L_NUM_NAV`" in doc
    assert "## Numbers & Navigation <sub>`L_NUM_NAV`</sub>" in doc
    assert doc.startswith("<!-- GENERATED by tools/gen_layer_schemes.py")

def test_layer_title_unknown_fatal():
    try:
        g.layer_title("L_TOTALLY_NEW")
    except SystemExit:
        pass
    else:
        raise AssertionError("unknown layer name should be fatal")

def test_regen_keymap_idempotent():
    src = g.KEYMAP.read_text(encoding="utf-8")
    once = g.regen_keymap(src)
    assert g.regen_keymap(once) == once
    assert "GENERATED scheme" in once

def test_regen_keymap_marks_every_layer():
    once = g.regen_keymap(g.KEYMAP.read_text(encoding="utf-8"))
    assert once.count("GENERATED scheme") == 7

def test_extract_combos_real():
    combos = g.extract_combos(g.KEYMAP.read_text(encoding="utf-8"))
    by_keys = {tuple(ks): act for ks, act in combos}
    assert by_keys[("KC_S", "KC_W")] == "KC_LBRC"
    assert by_keys[("KK_SHIFT", "KC_SPACE")] == "KC_ESC"
    assert len(combos) == 23

def test_extract_leader_seqs_real():
    seqs = g.extract_leader_seqs(g.KEYMAP.read_text(encoding="utf-8"))
    assert (["KC_R"], "Russian — compose backend (default)") in [(k, d) for k, d in seqs]
    assert (["KC_D", "KC_W"], "delete word (Ctrl+Backspace)") in [(k, d) for k, d in seqs]
    assert len(seqs) == 24

def test_extract_emoji_real():
    emo = g.extract_emoji(g.KEYMAP.read_text(encoding="utf-8"))
    assert ("t", "🌷") in emo and len(emo) == 11

def test_gen_doc_has_legend():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    assert "## Legend" in doc
    assert "- `sft` — one-shot Shift" in doc
    assert "- `pol` — mouse: polar mode" in doc
    # Legend now lives at the end, after the Emoji table.
    assert doc.index("## Legend") > doc.index("## Emoji")

def test_gen_doc_has_phase2_sections():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    for h in ["## Combos", "## Leader sequences", "## Emoji"]:
        assert h in doc

def test_gen_doc_has_toc():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    assert "## Contents" in doc
    # ToC sits near the top, before the first content section.
    assert doc.index("## Contents") < doc.index("## Base (BOO)")
    toc = doc.split("## Contents", 1)[1].split("\n## ", 1)[0]
    # Every other ## heading is linked, with the clean title and a resolving anchor.
    for h in re.findall(r"^## (.+)$", doc, re.M):
        if h == "Contents":
            continue
        title = re.sub(r"\s*<sub>.*?</sub>", "", h)
        assert f"- [{title}](#{g.gh_anchor(h)})" in toc, f"ToC missing {title!r}"
    # The tricky <sub> heading resolves to the tag-stripped slug, not #base-boo.
    assert "(#base-boo-l_boo)" in toc

def test_extract_design_real():
    design = g.extract_design(g.KEYMAP.read_text(encoding="utf-8"))
    assert "### Base layer" in design
    assert "[BOO layout](https://ballerboo.github.io/boolayout/)" in design
    for h in ["### Modifiers", "### Thumbs", "### Unicode input", "### Key comfort scores"]:
        assert h in design, h
    assert "pinky2 pinky" in design   # the comfort-score table survived
    assert "```" in design            # ...inside a fenced code block

def test_gen_doc_has_design():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    assert "## Design" in doc
    assert "### Modifiers" in doc
    # Design is an appendix: after Emoji, before Legend.
    assert doc.index("## Emoji") < doc.index("## Design") < doc.index("## Legend")
    # The comfort-score table stays preformatted (fenced), not a markdown table.
    design = doc.split("## Design", 1)[1]
    assert "pinky2 pinky" in design

def test_gh_anchor_slug():
    # GitHub's github-slugger: strip HTML tags, lowercase, drop a punctuation
    # blocklist (incl. backticks, parens, &, em dash), spaces -> hyphens. The
    # <sub>`enum`</sub> tail contributes its inner text (the enum) to the slug.
    assert g.gh_anchor("Combos") == "combos"
    assert g.gh_anchor("Base (BOO) <sub>`L_BOO`</sub>") == "base-boo-l_boo"
    assert g.gh_anchor("Numbers & Navigation <sub>`L_NUM_NAV`</sub>") == "numbers--navigation-l_num_nav"
    assert g.gh_anchor("Mouse — Polar <sub>`L_MOUSE`</sub>") == "mouse--polar-l_mouse"

def test_combo_board_real():
    src = g.KEYMAP.read_text(encoding="utf-8")
    base = dict(g.extract_layers(src))["L_BOO"]
    board = g.render_combo_board(base, g.extract_combos(src))
    # boxed, and rendered as two hands with a gap between them
    assert any(l.startswith("┌") and "    ┌" in l for l in board.splitlines())
    assert "┼" in board
    # every vertical same-column combo lands on a border label
    for lbl in ("Ctl", "Nav", "Alt", "Gui", "Fky", "[", "]", "(", ")", "<", ">", '"'):
        assert lbl in board, f"missing border label {lbl!r}"
    # the non-adjacent combos fall to the caption list, not a border
    assert "Other combos" in board
    for cap in ("Esc", "=>", "->", "bootloader", "reboot"):
        assert cap in board, f"missing caption {cap!r}"

def test_combo_board_only_home_anchors():
    src = g.KEYMAP.read_text(encoding="utf-8")
    base = dict(g.extract_layers(src))["L_BOO"]
    board = g.render_combo_board(base, g.extract_combos(src))
    # The keycap cells (│-separated rows) are blanked to leave only the 8 home
    # anchors as position markers; combo border labels & captions are untouched.
    cells = []
    for line in board.splitlines():
        if "│" in line:
            cells += [c.strip() for c in line.split("│")]
    values = sorted(c for c in cells if c)
    assert values == sorted(["a", "o", "e", "s", "n", "t", "r", "i"]), values

def test_combos_note_shifted_guillemets():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    combos = doc.split("## Combos", 1)[1].split("## Leader", 1)[0]
    # The <,> combos double as «,» under Shift — surfaced as a footnote, keyed
    # to the actual trigger keys so it stays in sync with the combo table.
    assert "«" in combos and "»" in combos
    assert "shift" in combos.lower()
    assert "g + z" in combos and "b + p" in combos

def test_gen_doc_combos_is_board():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    section = doc.split("## Combos")[1].split("## Leader")[0]
    assert "┌" in section and "┼" in section, "combos section is not the boxed board"
    assert "Ctl" in section and "[" in section

if __name__ == "__main__":
    test_layer_names(); test_extract_layers(); test_wrong_token_count_fatal()
    test_glyph_rules(); test_unknown_keycode_fatal(); test_real_keymap_fully_covered()
    test_render_grid_golden()
    test_doc_paragraph(); test_gen_doc_contains_all_layers()
    test_layer_title_unknown_fatal()
    test_regen_keymap_idempotent(); test_regen_keymap_marks_every_layer()
    test_extract_combos_real(); test_extract_leader_seqs_real()
    test_extract_emoji_real(); test_gen_doc_has_legend()
    test_gen_doc_has_phase2_sections()
    test_extract_design_real(); test_gen_doc_has_design()
    test_gh_anchor_slug(); test_gen_doc_has_toc()
    test_combo_board_real(); test_combo_board_only_home_anchors()
    test_combos_note_shifted_guillemets()
    test_gen_doc_combos_is_board()
    print("ok")
