#!/usr/bin/env python3
"""Off-target tests for gen_layer_schemes.py (layer-scheme generator)."""
import sys, os, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_layer_schemes as g

# 42 tokens: rows of 12/12/12 + 6 thumbs. Paren-nested token included on purpose.
TOKENS = (
    ["KC_Q"] * 11 + ["LT(L_SYMBOLS, KC_ENTER)"]
    + ["KC_A"] * 12
    + ["KC_Z"] * 12
    + ["KC_SPACE"] * 6
)

SNIPPET = (
    "enum my_layer_names {\n  L_ONE,\n  L_TWO,\n};\n"
    "const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {\n"
    "  [L_ONE] = LAYOUT_split_3x6_3(/* old scheme\n   q q q */\n    "
    + ", ".join(TOKENS)
    + "\n  ),\n"
    "  [L_TWO] = LAYOUT_split_3x6_3( // line comment\n    "
    + ", ".join(TOKENS)
    + "\n  ),\n"
    "};\n"
)

def test_layer_names():
    assert g.layer_names(SNIPPET) == ["L_ONE", "L_TWO"]

def test_extract_layers():
    layers = g.extract_layers(SNIPPET)
    assert [name for name, _ in layers] == ["L_ONE", "L_TWO"]
    for _, toks in layers:
        assert len(toks) == 42
        assert toks[11] == "LT(L_SYMBOLS, KC_ENTER)"  # comma inside parens kept
        assert toks[0] == "KC_Q" and toks[41] == "KC_SPACE"

def test_wrong_token_count_fatal():
    bad = SNIPPET.replace(", ".join(TOKENS), ", ".join(TOKENS[:41]), 1)
    try:
        g.extract_layers(bad)
    except SystemExit:
        pass
    else:
        raise AssertionError("41 tokens should be fatal")

def test_glyph_rules():
    assert g.glyph("KC_A") == "a"
    assert g.glyph("KC_7") == "7"
    assert g.glyph("KC_F12") == "F12"
    assert g.glyph("RU_YO") == "ё"
    assert g.glyph("__") == "__"
    assert g.glyph("XX") == "·"
    assert g.glyph("KC_BSPC") == "⌫"
    assert g.glyph("LT(L_SYMBOLS, KC_ENTER)") == "ret"
    assert g.glyph("KK_LEAD_L") == "LEAD" and g.glyph("KK_LEAD_R") == "LEAD"

def test_unknown_keycode_fatal():
    try:
        g.glyph("KC_TOTALLY_NEW")
    except SystemExit:
        pass
    else:
        raise AssertionError("unknown keycode should be fatal")

def test_real_keymap_fully_covered():
    src = g.KEYMAP.read_text(encoding="utf-8")
    layers = g.extract_layers(src)
    assert len(layers) == 6
    for name, toks in layers:
        for t in toks:
            g.glyph(t)  # SystemExit here = missing glyph for a real keycode

def test_render_grid_golden():
    toks = (
        ["KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Y"] + ["KC_U", "KC_I", "KC_O", "KC_P", "KC_A", "KC_S"]
        + ["XX", "KC_PGUP", "KC_D", "KC_F", "KC_G", "KC_H"] + ["KC_J", "KC_K", "KC_L", "KC_Z", "KC_X", "KC_C"]
        + ["__"] * 12
        + ["QK_LEAD", "KK_SHIFT", "KK_SYMBO", "KK_RET", "KC_SPACE", "QK_LEAD"]
    )
    # Golden derived from the renderer rules: per-column width = widest glyph
    # in that column over the 3 main rows ([2,3,2,2,...] here), cells joined by
    # 2 spaces, padded halves joined by 8 spaces, trailing whitespace stripped,
    # left thumb cluster right-aligned to the left half's end.
    expected = "\n".join([
        "q   w    e   r   t   y         u   i   o   p   a   s",
        "·   pg↑  d   f   g   h         j   k   l   z   x   c",
        "__  __   __  __  __  __        __  __  __  __  __  __",
        "         LEAD  sft  SYM        ret  spc  LEAD",
    ])
    assert g.render_grid(toks) == expected

def test_doc_paragraph():
    src = (
        "/**\n * Mouse layer — POLAR mode.\n *\n * More prose that is NOT the first paragraph.\n */\n"
        "  [L_ONE] = LAYOUT_split_3x6_3(\n    " + ", ".join(TOKENS) + "\n  ),"
    )
    assert g.doc_paragraph(src, "L_ONE") == "Mouse layer — POLAR mode."

def test_gen_doc_contains_all_layers():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    for title in ["Base (BOO)", "Russian", "Symbols", "Numbers & Navigation",
                  "F-keys & System", "Mouse — Polar"]:
        assert f"## {title}" in doc
    # friendly titles replace raw enum headings, but the enum survives in <sub>
    assert "## L_NUM_NAV" not in doc
    assert "`L_NUM_NAV`" in doc
    assert "## Numbers & Navigation <sub>`L_NUM_NAV`</sub>" in doc
    assert doc.startswith("<!-- GENERATED by tools/gen_layer_schemes.py")

def test_layer_title_unknown_fatal():
    try:
        g.layer_title("L_TOTALLY_NEW")
    except SystemExit:
        pass
    else:
        raise AssertionError("unknown layer name should be fatal")

def test_regen_keymap_idempotent():
    src = g.KEYMAP.read_text(encoding="utf-8")
    once = g.regen_keymap(src)
    assert g.regen_keymap(once) == once
    assert "GENERATED scheme" in once

def test_regen_keymap_marks_every_layer():
    once = g.regen_keymap(g.KEYMAP.read_text(encoding="utf-8"))
    assert once.count("GENERATED scheme") == 6

def test_extract_combos_real():
    combos = g.extract_combos(g.KEYMAP.read_text(encoding="utf-8"))
    by_keys = {tuple(ks): act for ks, act in combos}
    assert by_keys[("KC_S", "KC_W")] == "KC_LBRC"
    assert by_keys[("KK_SHIFT", "KC_SPACE")] == "KC_ESC"
    # boot = all 3 thumbs of a half; reset = outer + inner thumb of that half.
    assert by_keys[("KK_LEAD_L", "KK_SHIFT", "KK_SYMBO")] == "QK_BOOT"
    assert by_keys[("KK_RET", "KC_SPACE", "KK_LEAD_R")] == "QK_BOOT"
    assert by_keys[("KK_LEAD_L", "KK_SYMBO")] == "QK_REBOOT"
    assert by_keys[("KK_RET", "KK_LEAD_R")] == "QK_REBOOT"
    assert len(combos) == 26

def test_extract_leader_seqs_real():
    seqs = g.extract_leader_seqs(g.KEYMAP.read_text(encoding="utf-8"))
    assert (["KC_R"], "lead_ru", "Russian — compose backend (default)") in seqs
    assert (["KC_D", "KC_W"], "lead_del_word", "delete word (Ctrl+Backspace)") in seqs
    assert len(seqs) == 20
    # Mirror pairs share an action; grouping collapses the 20 rows to 15 entries.
    groups = g.group_leader_seqs(seqs)
    assert len(groups) == 15
    by_seqs = {tuple(map(tuple, ks)): doc for ks, doc in groups}
    assert by_seqs[(("KC_M", "KC_L"), ("KC_DOT", "KC_L"))] == "₺ lira"

def test_bold_selector():
    assert g.bold_selector("tulip", "t") == "**t**ulip"
    assert g.bold_selector("think", "k") == "thin**k**"       # not word-initial
    assert g.bold_selector("handshake", "n") == "ha**n**dshake"
    assert g.bold_selector("thumbup", "u") == "th**u**mbup"   # first occurrence

def test_leader_seqs_grouped_with_diagrams():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    lead = doc.split("## Leader sequences", 1)[1].split("## Emoji", 1)[0]
    # Mirror pairs collapse into one entry naming both hands.
    assert "`LEAD, m, l` / `LEAD, ., l`" in lead
    # (mirror ...) annotations are stripped from the rendered descriptions.
    assert "mirror" not in lead
    # Single (non-mirrored) sequences still appear on their own.
    assert "`LEAD, v`" in lead
    # Each entry carries a numbered position diagram (LEAD=0, keys 1,2,...) —
    # combos keep ●, leaders are ordered so they read as "press here, then here".
    assert "0 · ·   · · 0" in lead
    assert "●" not in lead

def test_insert_toc_requires_sections():
    # Fail loud (die), not a bare StopIteration, if there are no ## sections.
    try:
        g.insert_toc(["# Title", "", "prose but no sections"])
    except SystemExit:
        pass
    else:
        raise AssertionError("insert_toc with no ## sections should be fatal")

def test_group_leader_seqs_rejects_divergent_docs():
    # Two mirror rows whose descriptions diverge (beyond the trailing qualifier)
    # is source drift — the generator should die, not silently keep the first.
    bad = [(["KC_S"], "lead_esc", "Esc + exit toggle layer (mirror pair s·n)"),
           (["KC_N"], "lead_esc", "Escape and leave (mirror pair s·n)")]
    try:
        g.group_leader_seqs(bad)
    except SystemExit:
        pass
    else:
        raise AssertionError("divergent mirror-pair docs should be fatal")
    # ...but a trailing-qualifier difference (default vs mirror-of) is allowed.
    ok = [(["KC_R"], "lead_ru", "Russian — compose backend (default)"),
          (["KC_C"], "lead_ru", "Russian — compose backend (mirror of r)")]
    (seqs, doc), = g.group_leader_seqs(ok)
    assert doc == "Russian — compose backend (default)"

def test_extract_emoji_real():
    emo = g.extract_emoji(g.KEYMAP.read_text(encoding="utf-8"))
    assert ("t", "🌷", "tulip") in emo and len(emo) == 11

def test_emoji_table_bolds_word():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    emoji = doc.split("## Emoji", 1)[1].split("## Design", 1)[0]
    assert "**t**ulip" in emoji and "thin**k**" in emoji and "ha**n**dshake" in emoji

def test_gen_doc_has_legend():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    assert "## Legend" in doc
    assert "- `sft` — one-shot Shift" in doc
    assert "- `pol` — mouse: polar mode" in doc
    # Legend now lives at the end, after the Emoji table.
    assert doc.index("## Legend") > doc.index("## Emoji")

def test_gen_doc_has_phase2_sections():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    for h in ["## Combos", "## Leader sequences", "## Emoji"]:
        assert h in doc

def test_gen_doc_has_toc():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    assert "## Contents" in doc
    # ToC sits near the top, before the first content section.
    assert doc.index("## Contents") < doc.index("## Base (BOO)")
    toc = doc.split("## Contents", 1)[1].split("\n## ", 1)[0]
    # Every other ## heading is linked, with the clean title and a resolving anchor.
    for h in re.findall(r"^## (.+)$", doc, re.M):
        if h == "Contents":
            continue
        title = re.sub(r"\s*<sub>.*?</sub>", "", h)
        assert f"- [{title}](#{g.gh_anchor(h)})" in toc, f"ToC missing {title!r}"
    # The tricky <sub> heading resolves to the tag-stripped slug, not #base-boo.
    assert "(#base-boo-l_boo)" in toc

def test_extract_design_real():
    design = g.extract_design(g.KEYMAP.read_text(encoding="utf-8"))
    assert "### Base layer" in design
    assert "[BOO layout](https://ballerboo.github.io/boolayout/)" in design
    for h in ["### Modifiers", "### Thumbs", "### Unicode input", "### Key comfort scores"]:
        assert h in design, h
    assert "pinky2 pinky" in design   # the comfort-score table survived
    assert "```" in design            # ...inside a fenced code block

def test_gen_doc_has_design():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    assert "## Design" in doc
    assert "### Modifiers" in doc
    # Design is an appendix: after Emoji, before Legend.
    assert doc.index("## Emoji") < doc.index("## Design") < doc.index("## Legend")
    # The comfort-score table stays preformatted (fenced), not a markdown table.
    design = doc.split("## Design", 1)[1]
    assert "pinky2 pinky" in design

def test_design_modifiers_justification_is_honest():
    design = g.extract_design(g.KEYMAP.read_text(encoding="utf-8"))
    mods = design.split("### Modifiers", 1)[1].split("###", 1)[0]
    # The old hand-wave (misfires avoided because "you never press two keys of a
    # column with one finger") is discredited — it is gone.
    assert "never press two keys of one column with a single finger" not in mods
    # The honest reason: choc spacing makes the pair an easy "extra key" reached
    # by finger placement; ordinary typing aims at key centers, so no accident.
    assert "placement" in mods
    assert "extra key" in mods

def test_gh_anchor_slug():
    # GitHub's github-slugger: strip HTML tags, lowercase, drop a punctuation
    # blocklist (incl. backticks, parens, &, em dash), spaces -> hyphens. The
    # <sub>`enum`</sub> tail contributes its inner text (the enum) to the slug.
    assert g.gh_anchor("Combos") == "combos"
    assert g.gh_anchor("Base (BOO) <sub>`L_BOO`</sub>") == "base-boo-l_boo"
    assert g.gh_anchor("Numbers & Navigation <sub>`L_NUM_NAV`</sub>") == "numbers--navigation-l_num_nav"
    assert g.gh_anchor("Mouse — Polar <sub>`L_MOUSE`</sub>") == "mouse--polar-l_mouse"

def test_combo_board_real():
    src = g.KEYMAP.read_text(encoding="utf-8")
    base = dict(g.extract_layers(src))["L_BOO"]
    board = g.render_combo_board(base, g.extract_combos(src))
    # boxed, and rendered as two hands with a gap between them
    assert any(l.startswith("┌") and "    ┌" in l for l in board.splitlines())
    assert "┼" in board
    # every vertical same-column combo lands on a border label
    for lbl in ("Ctl", "Nav", "Alt", "Gui", "Fky", "[", "]", "(", ")", "<", ">", '"'):
        assert lbl in board, f"missing border label {lbl!r}"
    # non-adjacent combos are no longer captioned on the board — they move out
    assert "Other combos" not in board
    nonadj = g.nonadjacent_combos(base, g.extract_combos(src))
    assert len(nonadj) == 8
    assert {"KC_ESC", "QK_BOOT", "QK_REBOOT",
            "KK_RIGHT_ARROW"} == {o for _k, o in nonadj}

def test_combo_board_only_home_anchors():
    src = g.KEYMAP.read_text(encoding="utf-8")
    base = dict(g.extract_layers(src))["L_BOO"]
    board = g.render_combo_board(base, g.extract_combos(src))
    # The keycap cells (│-separated rows) are blanked to leave only the 8 home
    # anchors as position markers; combo border labels & captions are untouched.
    cells = []
    for line in board.splitlines():
        if "│" in line:
            cells += [c.strip() for c in line.split("│")]
    values = sorted(c for c in cells if c)
    assert values == sorted(["a", "o", "e", "s", "n", "t", "r", "i"]), values

def test_position_diagram_marks():
    # 3 main rows (12 cols, split 6+6) + a thumb row; every cell a dot, hits ●.
    d = g.render_position_diagram({16})            # KC_S = home row, left col 4
    lines = d.splitlines()
    assert len(lines) == 4
    assert lines[0] == "· · · · · ·       · · · · · ·"
    assert lines[1] == "· · · · ● ·       · · · · · ·"
    # Esc = both middle thumbs (tokens 37, 40) -> two hits on the thumb row only.
    thumbs = g.render_position_diagram({37, 40}).splitlines()
    assert thumbs[0] == "· · · · · ·       · · · · · ·"
    assert thumbs[3].count("●") == 2 and thumbs[3].strip() == "· ● ·   · ● ·"

def test_position_diagram_labels():
    # An optional labels dict overrides a position's mark with its own text —
    # used to number leader steps instead of the anonymous ● hit.
    d = g.render_position_diagram(set(), labels={16: "1"})   # KC_S home row
    assert d.splitlines()[1] == "· · · · 1 ·       · · · · · ·"
    # LEAD lives on both outer thumbs (tokens 36 & 41); number them 0.
    thumbs = g.render_position_diagram(set(), labels={36: "0", 41: "0"}).splitlines()
    assert thumbs[3].strip() == "0 · ·   · · 0"
    # The plain marks path is untouched: a set still renders ●.
    assert g.render_position_diagram({16}).splitlines()[1] == "· · · · ● ·       · · · · · ·"

def test_leader_labels():
    base = dict(g.extract_layers(g.KEYMAP.read_text(encoding="utf-8")))["L_BOO"]
    def at(tok):
        (i,) = [j for j, t in enumerate(base) if t == tok]
        return i
    # LEAD (both outer thumbs) is step 0; the key after it is 1.
    labels = g.leader_labels(base, [["KC_V"]])
    assert labels[36] == "0" and labels[41] == "0"
    assert labels[at("KC_V")] == "1"
    # A two-key leader numbers the keys in press order: d -> 1, w -> 2.
    labels = g.leader_labels(base, [["KC_D", "KC_W"]])
    assert labels[at("KC_D")] == "1" and labels[at("KC_W")] == "2"
    # A mirror pair shares step numbers across both hands: s and n both -> 1.
    labels = g.leader_labels(base, [["KC_S"], ["KC_N"]])
    assert labels[at("KC_S")] == "1" and labels[at("KC_N")] == "1"

def test_leader_diagrams_numbered():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    lead = doc.split("## Leader sequences", 1)[1].split("## Emoji", 1)[0]
    # Leader diagrams number the presses (LEAD=0, then 1,2,...) — no anonymous ●.
    assert "●" not in lead
    assert "0 · ·   · · 0" in lead          # LEAD drawn as 0 on both outer thumbs
    # The two-key 'delete word' (LEAD, d, w) DIAGRAM itself carries steps 1 and 2
    # — assert inside its fenced block, not the header prose (which literally says
    # "1, 2" and would make a bare `"2" in lead` pass even if numbering broke).
    dw_diagram = lead.split("`LEAD, d, w`", 1)[1].split("```", 2)[1]
    assert "1" in dw_diagram and "2" in dw_diagram

def test_leader_labels_rejects_divergent_step():
    # Assigning one base position two different step numbers within a group is
    # drift — fail loud rather than silently mislabel (matches group_leader_seqs).
    base = dict(g.extract_layers(g.KEYMAP.read_text(encoding="utf-8")))["L_BOO"]
    try:
        g.leader_labels(base, [["KC_D", "KC_A"], ["KC_A", "KC_D"]])  # d,a vs a,d
    except SystemExit:
        pass
    else:
        raise AssertionError("divergent leader step labels should be fatal")

def test_base_has_split_leader_no_noop():
    base = dict(g.extract_layers(g.KEYMAP.read_text(encoding="utf-8")))["L_BOO"]
    # KK_NOOP is retired; the two outer thumbs carry distinct leader keycodes so
    # the reset chord (both of them) is an unambiguous combo.
    assert "KK_NOOP" not in base
    assert base[36] == "KK_LEAD_L" and base[41] == "KK_LEAD_R"
    # the retired np corners are now plain no-ops
    assert base[24] == "XX" and base[35] == "XX"

def test_resolve_positions_reset_and_boot_combos():
    base = dict(g.extract_layers(g.KEYMAP.read_text(encoding="utf-8")))["L_BOO"]
    # boot = all three thumbs of a half; reset = outer + inner thumb of that half.
    assert set(g.resolve_positions(base, ["KK_LEAD_L", "KK_SHIFT", "KK_SYMBO"])) == {36, 37, 38}
    assert set(g.resolve_positions(base, ["KK_RET", "KC_SPACE", "KK_LEAD_R"])) == {39, 40, 41}
    assert set(g.resolve_positions(base, ["KK_LEAD_L", "KK_SYMBO"])) == {36, 38}
    assert set(g.resolve_positions(base, ["KK_RET", "KK_LEAD_R"])) == {39, 41}

def test_resolve_positions_disambiguates_two_handed_key():
    # A key present on both hands resolves to the hand of its unambiguous chord
    # mate. No current combo needs this, but the generator stays robust to one.
    base = (["XX"] * 23 + ["DUP"]          # right end of row 1 (index 23)...
            + ["DUP"] + ["XX"] * 11        # ...and left start of row 2 (index 24)
            + ["QK_LEAD", "KK_SHIFT", "KK_SYMBO", "KK_RET", "KC_SPACE", "QK_LEAD"])
    assert len(base) == 42
    # chorded with the left-thumb shift -> the left DUP (24), not the right (23).
    assert set(g.resolve_positions(base, ["DUP", "KK_SHIFT"])) == {24, 37}

def test_combos_note_shifted_guillemets():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    combos = doc.split("## Combos", 1)[1].split("## Leader", 1)[0]
    # The <,> combos double as «,» under Shift — surfaced as a footnote, keyed
    # to the actual trigger keys so it stays in sync with the combo table.
    assert "«" in combos and "»" in combos
    assert "shift" in combos.lower()
    assert "g + z" in combos and "b + p" in combos

def test_nonadjacent_combos_have_diagrams():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    combos = doc.split("## Combos", 1)[1].split("## Leader", 1)[0]
    assert "┌" in combos                          # the boxed board is still there
    # the non-adjacent combos are described AND diagrammed (thumbs included)
    assert "sft + spc → Esc" in combos
    assert "h + m → Esc" in combos
    assert ". + w → Esc" in combos
    # boot = all three thumbs of a half; reset = outer + inner thumb of that half
    assert "LEAD + sft + SYM → bootloader" in combos
    assert "ret + spc + LEAD → bootloader" in combos
    assert "LEAD + SYM → reboot" in combos
    assert "ret + LEAD → reboot" in combos
    assert "np" not in combos            # the retired no-op filler is gone
    # Esc fires on both middle thumbs -> its diagram thumb-row shows two hits
    assert "· ● ·   · ● ·" in combos

def test_gen_doc_combos_is_board():
    doc = g.gen_doc(g.KEYMAP.read_text(encoding="utf-8"))
    section = doc.split("## Combos")[1].split("## Leader")[0]
    assert "┌" in section and "┼" in section, "combos section is not the boxed board"
    assert "Ctl" in section and "[" in section

if __name__ == "__main__":
    test_layer_names(); test_extract_layers(); test_wrong_token_count_fatal()
    test_glyph_rules(); test_unknown_keycode_fatal(); test_real_keymap_fully_covered()
    test_render_grid_golden()
    test_doc_paragraph(); test_gen_doc_contains_all_layers()
    test_layer_title_unknown_fatal()
    test_regen_keymap_idempotent(); test_regen_keymap_marks_every_layer()
    test_extract_combos_real(); test_extract_leader_seqs_real()
    test_insert_toc_requires_sections(); test_group_leader_seqs_rejects_divergent_docs()
    test_leader_seqs_grouped_with_diagrams()
    test_bold_selector(); test_extract_emoji_real(); test_emoji_table_bolds_word()
    test_gen_doc_has_legend()
    test_gen_doc_has_phase2_sections()
    test_extract_design_real(); test_gen_doc_has_design()
    test_design_modifiers_justification_is_honest()
    test_gh_anchor_slug(); test_gen_doc_has_toc()
    test_combo_board_real(); test_combo_board_only_home_anchors()
    test_position_diagram_marks(); test_position_diagram_labels()
    test_leader_labels(); test_leader_diagrams_numbered()
    test_leader_labels_rejects_divergent_step()
    test_base_has_split_leader_no_noop()
    test_resolve_positions_reset_and_boot_combos()
    test_resolve_positions_disambiguates_two_handed_key()
    test_combos_note_shifted_guillemets()
    test_nonadjacent_combos_have_diagrams()
    test_gen_doc_combos_is_board()
    print("ok")
