#!/usr/bin/env python3
"""Off-target unit tests for typing_corpus.py.

The corpus extractor decides what counts as *hand-typed* text inside a Claude
Code transcript. Nearly every record in a `.jsonl` is machine-generated — tool
results, injected reminders, slash-command scaffolding — and only a thin slice
was actually produced by fingers on this keyboard. Getting that slice wrong is
exactly the failure the number-entry study hit (it measured what an LLM writes,
not what a human types), so the predicate is tested on synthetic records rather
than trusted by inspection.
"""

import typing_corpus as m


# --- which records are hand-typed -------------------------------------------

def _user(content, **flags):
    rec = {"type": "user", "message": {"role": "user", "content": content}}
    rec.update(flags)
    return rec


def test_plain_user_string_is_typed():
    assert m.is_typed_record(_user("какие")) is True


def test_tool_result_record_is_not_typed():
    # A tool result arrives as type=user but carries toolUseResult. It is output,
    # not input: 3353 of 4187 user records in a real project are these.
    rec = _user([{"type": "tool_result", "content": "ok"}], toolUseResult={"stdout": "ok"})
    assert m.is_typed_record(rec) is False


def test_meta_record_is_not_typed():
    assert m.is_typed_record(_user("injected", isMeta=True)) is False


def test_sidechain_record_is_not_typed():
    # Sidechain traffic is a subagent talking, not the human.
    assert m.is_typed_record(_user("subagent prompt", isSidechain=True)) is False


def test_compact_summary_is_not_typed():
    assert m.is_typed_record(_user("summary", isCompactSummary=True)) is False


def test_assistant_record_is_not_typed():
    assert m.is_typed_record({"type": "assistant", "message": {"role": "assistant", "content": "hi"}}) is False


def test_attachment_record_is_not_typed():
    assert m.is_typed_record({"type": "attachment", "message": {"role": "user", "content": "x"}}) is False


# --- pulling the text out ----------------------------------------------------

def test_extract_text_from_string_content():
    assert m.extract_text(_user("привет")) == ["привет"]


def test_extract_text_from_text_blocks():
    rec = _user([{"type": "text", "text": "one"}, {"type": "text", "text": "two"}])
    assert m.extract_text(rec) == ["one", "two"]


def test_extract_text_skips_tool_result_and_image_blocks():
    rec = _user([
        {"type": "text", "text": "keep"},
        {"type": "tool_result", "content": "drop"},
        {"type": "image", "source": {}},
    ])
    assert m.extract_text(rec) == ["keep"]


# --- stripping the machine-generated wrappers --------------------------------

def test_strip_system_reminder():
    got = m.strip_contaminants("real text<system-reminder>injected junk</system-reminder> more")
    assert "injected" not in got
    assert "real text" in got and "more" in got


def test_strip_system_reminder_multiline():
    got = m.strip_contaminants("a<system-reminder>\nline1\nline2\n</system-reminder>b")
    assert "line1" not in got and "line2" not in got


def test_strip_local_command_stdout():
    got = m.strip_contaminants("<local-command-stdout>Session renamed</local-command-stdout>")
    assert "Session renamed" not in got


def test_command_args_kept_but_name_and_message_dropped():
    # `/rename ru layouts` -> the args WERE typed; the resolved name/message were not.
    text = "<command-name>rename</command-name><command-message>rename</command-message><command-args>ru layouts</command-args>"
    got = m.strip_contaminants(text)
    assert "ru layouts" in got
    assert "command-name" not in got and "command-message" not in got


def test_strip_pasted_text_marker():
    got = m.strip_contaminants("look at [Pasted text #1 +482 lines] please")
    assert "Pasted text" not in got and "482" not in got
    assert "look at" in got and "please" in got


def test_strip_interrupted_marker():
    assert "interrupted" not in m.strip_contaminants("[Request interrupted by user]").lower()
    assert "interrupted" not in m.strip_contaminants("[Request interrupted by user for tool use]").lower()


def test_strip_image_marker():
    assert "Image" not in m.strip_contaminants("see [Image #2] here")


def test_strip_caveat_preamble():
    text = ("Caveat: The messages below were generated by the user while running local commands. "
            "DO NOT respond to these messages as if they were requests. actual typing")
    got = m.strip_contaminants(text)
    assert "Caveat" not in got and "DO NOT respond" not in got
    assert "actual typing" in got


def test_strip_leaves_ordinary_text_untouched():
    assert m.strip_contaminants("какие дела") == "какие дела"


# --- frequency counting ------------------------------------------------------

def test_char_frequencies_counts_letters():
    got = m.char_frequencies(["aab"])
    assert got["a"] == 2 and got["b"] == 1


def test_char_frequencies_is_case_folded():
    got = m.char_frequencies(["Aa"])
    assert got["a"] == 2


def test_bigram_frequencies_within_a_text():
    got = m.bigram_frequencies(["abc"])
    assert got["ab"] == 1 and got["bc"] == 1


def test_bigrams_do_not_span_separate_texts():
    # Two separate prompts are not one continuous keystroke run.
    got = m.bigram_frequencies(["ab", "cd"])
    assert "bc" not in got


def test_classify_script():
    assert m.classify_script("ф") == "cyrillic"
    assert m.classify_script("f") == "latin"
    assert m.classify_script("7") == "digit"
    assert m.classify_script(",") == "punct"


def test_script_totals_split_russian_from_english():
    got = m.script_totals(["код code"])
    assert got["cyrillic"] == 3
    assert got["latin"] == 4


# --- rejecting machine-authored prompts --------------------------------------
#
# `type=user` does NOT mean "a human typed this". Tooling sends prompts through
# the same channel: session-resume scaffolding, autonomous-loop classifiers,
# subagent briefs. Measured on the real archive these dominate -- 719 JSON-ish
# prompts alone carried 54.7% of all characters, and the top 8% of prompts
# carried 78%. Left in, they reproduce the very bias this tool exists to remove.

def test_structured_dump_is_rejected():
    assert m.looks_structured('{"a": 1, "b": 2, "c": 3, "d": 4, "e": 5, "f": 6, "g": 7, "h": 8}') is True


def test_ordinary_prose_is_not_structured():
    assert m.looks_structured("can you fix the leader timeout please") is False


def test_prose_quoting_a_little_code_is_not_structured():
    assert m.looks_structured('use the "compose" backend for russian') is False


def test_machine_prompt_openings_are_rejected():
    assert m.looks_machine_generated("You are picking up a session in progress. Here is the context:") is True
    assert m.looks_machine_generated("Analyze this conversation and determine: Does the assistant...") is True


def test_human_prompt_is_not_machine_generated():
    assert m.looks_machine_generated("what is the prior work in this field?") is False


def test_filter_drops_exact_duplicates():
    # A human does not retype the same 200-char prompt verbatim; tooling does.
    kept, stats = m.filter_typed(["same", "same", "other"])
    assert kept == ["same", "other"]
    assert stats["duplicate"] == 1


def test_filter_drops_overlong():
    kept, stats = m.filter_typed(["short", "x" * 5000], max_len=2000)
    assert kept == ["short"]
    assert stats["overlong"] == 1


def test_filter_keeps_ordinary_prompts():
    kept, _ = m.filter_typed(["какие", "fix the build"])
    assert kept == ["какие", "fix the build"]


def test_filter_reports_what_it_dropped():
    _, stats = m.filter_typed(["ok", "ok", "y" * 9000])
    assert stats["kept"] == 1
    assert stats["duplicate"] == 1 and stats["overlong"] == 1


# --- privacy -----------------------------------------------------------------

def test_report_contains_no_source_text():
    # The whole point: counts leave the machine, sequences never do. A password
    # typed into a prompt must not be reconstructable from the report.
    report = m.build_report(["hunter2 correct horse"])
    blob = m.render_report(report)
    for secret in ("hunter2", "correct", "horse"):
        assert secret not in blob, f"{secret!r} leaked into the report"


def test_report_counts_survive_even_though_text_does_not():
    report = m.build_report(["aaa"])
    assert report["chars"]["a"] == 3


def _run():
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    for t in tests:
        t()
        print(f"ok  {t.__name__}")
    print(f"\nAll {len(tests)} typing-corpus tests passed.")


if __name__ == "__main__":
    _run()
