#!/usr/bin/env python3
"""Build a hand-typed character corpus from Claude Code transcripts.

Every layout decision on this board has so far been made against the wrong
sample. The number-entry study measured repo code and markdown -- which is
largely LLM-written -- so its punctuation frequencies described what Claude
generates, not what fingers do (`;` swung 70x across corpora). This tool fixes
the input: `~/.claude/projects/**/*.jsonl` holds thousands of sessions whose
user-message text is close to 100% hand-typed on this keyboard.

The hard part is deciding what "hand-typed" means. Almost nothing in a
transcript qualifies -- in a real project only ~835 of 4187 `type=user` records
carry typed text, the other 3353 being tool results wearing a user-shaped
record. Injected reminders, slash-command scaffolding, paste markers and
interrupt notices all arrive inside otherwise-genuine prompts. Those rules live
in `is_typed_record` / `extract_text` / `strip_contaminants` and are unit-tested
on synthetic records, because a silent mistake here reproduces exactly the bug
this tool exists to remove.

PRIVACY -- this reads everything the user has ever typed to Claude, which
includes secrets. So it emits **counts, never sequences**: unigram and bigram
totals only, no 3-grams, no source text, nothing written that could be read back
as a prompt. That is not merely a concession -- frequency tables are also the
native input format for layout optimisers (klavarog/OPT reads `.1`/`.2`
frequency files directly), so the private form is also the useful one.
"""

import argparse
import collections
import json
import os
import re
import sys
import unicodedata

# --- what is not hand-typed ---------------------------------------------------

# Flags that mark a user-shaped record as machine-origin.
_NOT_TYPED_FLAGS = ("isMeta", "isSidechain", "isCompactSummary", "isVisibleInTranscriptOnly")

# `<command-args>` is the one wrapper whose *contents* were typed: for
# `/rename ru layouts` the resolved name and echoed message are generated, but
# "ru layouts" came off the keyboard. Unwrap it before the tags are stripped.
_COMMAND_ARGS = re.compile(r"<command-args>(.*?)</command-args>", re.S | re.I)

_CONTAMINANTS = (
    re.compile(r"<system-reminder>.*?</system-reminder>", re.S | re.I),
    re.compile(r"<local-command-stdout>.*?</local-command-stdout>", re.S | re.I),
    re.compile(r"<command-message>.*?</command-message>", re.S | re.I),
    re.compile(r"<command-name>.*?</command-name>", re.S | re.I),
    re.compile(r"<user-prompt-submit-hook>.*?</user-prompt-submit-hook>", re.S | re.I),
    # Paste is a clipboard event, not keystrokes -- the whole point is to count
    # what fingers did.
    re.compile(r"\[Pasted text[^\]]*\]", re.I),
    re.compile(r"\[Image #\d+\]", re.I),
    re.compile(r"\[Request interrupted[^\]]*\]", re.I),
    re.compile(
        r"Caveat: The messages below were generated by the user while running local commands\.\s*"
        r"DO NOT respond to these messages as if they were requests\.\s*",
        re.I,
    ),
)


def is_typed_record(rec):
    """True if this transcript record holds text a human typed."""
    if not isinstance(rec, dict):
        return False
    if rec.get("type") != "user":
        return False
    # A tool result is output arriving in a user-shaped envelope.
    if rec.get("toolUseResult") is not None:
        return False
    if any(rec.get(f) for f in _NOT_TYPED_FLAGS):
        return False
    message = rec.get("message") or {}
    if message.get("role") != "user":
        return False
    return True


def extract_text(rec):
    """Return the typed text fragments of a record, dropping non-text blocks."""
    content = (rec.get("message") or {}).get("content")
    if isinstance(content, str):
        return [content]
    if not isinstance(content, list):
        return []
    out = []
    for block in content:
        if isinstance(block, dict) and block.get("type") == "text":
            out.append(block.get("text", ""))
    return out


def strip_contaminants(text):
    """Remove machine-generated wrappers, keeping only what was typed."""
    text = _COMMAND_ARGS.sub(lambda m: m.group(1), text)
    for pattern in _CONTAMINANTS:
        text = pattern.sub("", text)
    return text.strip()


# --- rejecting machine-authored prompts ---------------------------------------
#
# `type=user` is a channel, not an author. Tooling sends prompts down it too:
# session-resume scaffolding, autonomous-loop classifiers, subagent briefs.
# Measured on the real archive they are not a rounding error but the bulk of the
# data -- 719 JSON-ish prompts carried 54.7% of all characters, the top 8% of
# prompts carried 78%, and the single longest "prompts" were resume scaffolds
# repeated byte-identically. Counting them would rebuild the exact bias this
# tool exists to remove, so they are dropped and the drops are reported.

_STRUCTURAL = '"{}[]:,'

# Openings observed on the worst offenders in the real archive. This list is
# evidence-driven, not exhaustive -- dedup and the length cap are the general
# defences; this catches the repeat scaffolds that survive both.
_MACHINE_OPENINGS = (
    "you are picking up a session in progress",
    "analyze this conversation and determine",
    "you are an ai assistant",
    "here is the context:",
    "<session-restore>",
)


def looks_structured(text, threshold=0.15, min_len=30):
    """True if the text reads as a data dump rather than prose.

    JSON, logs and config pasted into a prompt are dense in `"{}[]:,`; typed
    prose quoting an identifier or two is not. Short strings are exempt so a
    human writing `{}` is not mistaken for a dump."""
    if len(text) < min_len:
        return False
    structural = sum(text.count(c) for c in _STRUCTURAL)
    return structural / len(text) > threshold


def looks_machine_generated(text):
    """True if the text opens like a programmatically-issued prompt."""
    head = text.lstrip().lower()[:200]
    return any(head.startswith(o) or o in head[:80] for o in _MACHINE_OPENINGS)


def filter_typed(texts, max_len=2000):
    """Keep plausibly hand-typed prompts; return (kept, stats).

    `stats` records every drop reason so a run can never quietly claim to have
    measured more than it did."""
    stats = collections.Counter()
    seen = set()
    kept = []
    for text in texts:
        if text in seen:
            stats["duplicate"] += 1
            continue
        seen.add(text)
        if looks_machine_generated(text):
            stats["machine"] += 1
            continue
        if looks_structured(text):
            stats["structured"] += 1
            continue
        if len(text) > max_len:
            stats["overlong"] += 1
            continue
        kept.append(text)
    stats["kept"] = len(kept)
    return kept, stats


# --- counting -----------------------------------------------------------------

_PUNCT_CATEGORIES = ("Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po", "Sm", "Sc", "Sk")


def classify_script(ch):
    """Bucket a character: cyrillic / latin / digit / punct / space / other."""
    if ch.isspace():
        return "space"
    if ch.isdigit():
        return "digit"
    if ch.isalpha():
        try:
            name = unicodedata.name(ch)
        except ValueError:
            return "other"
        if "CYRILLIC" in name:
            return "cyrillic"
        if "LATIN" in name:
            return "latin"
        return "other"
    if unicodedata.category(ch) in _PUNCT_CATEGORIES:
        return "punct"
    return "other"


def char_frequencies(texts):
    """Case-folded unigram counts across the given texts."""
    counts = collections.Counter()
    for text in texts:
        counts.update(text.lower())
    return counts


def bigram_frequencies(texts):
    """Case-folded bigram counts. Bigrams never span two separate prompts --
    those are two different keystroke runs, not one continuous roll."""
    counts = collections.Counter()
    for text in texts:
        low = text.lower()
        for a, b in zip(low, low[1:]):
            counts[a + b] += 1
    return counts


def script_totals(texts):
    """Character counts per script bucket."""
    totals = collections.Counter()
    for text in texts:
        for ch in text:
            totals[classify_script(ch)] += 1
    return totals


def build_report(texts):
    """Aggregate counts only -- no source text is retained."""
    chars = char_frequencies(texts)
    return {
        "chars": chars,
        "bigrams": bigram_frequencies(texts),
        "scripts": script_totals(texts),
        "n_texts": len(texts),
        "n_chars": sum(chars.values()),
    }


# --- transcript walking -------------------------------------------------------

def typed_texts_from_lines(lines):
    """Yield cleaned, hand-typed fragments from raw jsonl lines."""
    for line in lines:
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except (ValueError, TypeError):
            continue
        if not is_typed_record(rec):
            continue
        for fragment in extract_text(rec):
            cleaned = strip_contaminants(fragment)
            if cleaned:
                yield cleaned


def typed_texts_from_dir(root):
    """Walk every transcript under `root`, yielding hand-typed fragments."""
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in sorted(filenames):
            if not name.endswith(".jsonl"):
                continue
            path = os.path.join(dirpath, name)
            try:
                with open(path, encoding="utf-8", errors="replace") as fh:
                    for text in typed_texts_from_lines(fh):
                        yield text
            except OSError:
                continue


# --- rendering ----------------------------------------------------------------

def render_report(report, top=30):
    """Render counts. Emits unigrams and bigrams only -- never a longer run, so
    no typed word can be read back out of the output."""
    lines = []
    scripts = report["scripts"]
    total = report["n_chars"] or 1
    lines.append(f"prompts: {report['n_texts']}   characters: {report['n_chars']}")
    lines.append("")
    lines.append("script mix")
    for bucket, n in sorted(scripts.items(), key=lambda kv: -kv[1]):
        lines.append(f"  {bucket:<10} {n:>10}  {100.0 * n / total:5.2f}%")
    lines.append("")
    lines.append(f"top {top} characters")
    for ch, n in report["chars"].most_common(top):
        lines.append(f"  {_display(ch):<10} {n:>10}  {100.0 * n / total:5.2f}%")
    lines.append("")
    lines.append(f"top {top} bigrams")
    btotal = sum(report["bigrams"].values()) or 1
    for bg, n in report["bigrams"].most_common(top):
        lines.append(f"  {_display(bg):<10} {n:>10}  {100.0 * n / btotal:5.2f}%")
    return "\n".join(lines)


def _display(s):
    return "".join({" ": "␣", "\n": "⏎", "\t": "⇥"}.get(c, c) for c in s)


def write_frequency_files(report, out_dir, prefix="corpus"):
    """Write `.1`/`.2` frequency files -- the format layout optimisers consume."""
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for suffix, key in (("1", "chars"), ("2", "bigrams")):
        path = os.path.join(out_dir, f"{prefix}.{suffix}")
        with open(path, "w", encoding="utf-8") as fh:
            for gram, n in report[key].most_common():
                if any(c.isspace() for c in gram):
                    continue
                fh.write(f"{n}\t{gram}\n")
        written.append(path)
    return written


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--projects", default=os.path.expanduser("~/.claude/projects"),
                    help="root of Claude Code transcripts")
    ap.add_argument("--top", type=int, default=30, help="how many n-grams to show")
    ap.add_argument("--script", choices=["all", "cyrillic", "latin"], default="all",
                    help="restrict counting to one script (cyrillic drives the RU layout)")
    ap.add_argument("--out-dir", help="also write .1/.2 frequency files here")
    ap.add_argument("--max-len", type=int, default=2000,
                    help="drop prompts longer than this (median real prompt is ~67 chars)")
    ap.add_argument("--no-filter", action="store_true",
                    help="skip machine-prompt filtering (shows the raw, contaminated numbers)")
    args = ap.parse_args(argv)

    if not os.path.isdir(args.projects):
        print(f"no transcripts at {args.projects}", file=sys.stderr)
        return 1

    texts = list(typed_texts_from_dir(args.projects))
    raw_chars = sum(len(t) for t in texts)
    if args.no_filter:
        stats = collections.Counter(kept=len(texts))
    else:
        texts, stats = filter_typed(texts, max_len=args.max_len)
    dropped = sum(v for k, v in stats.items() if k != "kept")
    kept_chars = sum(len(t) for t in texts)
    print(f"prompts kept {stats['kept']} of {stats['kept'] + dropped}  "
          f"(dropped: duplicate {stats['duplicate']}, machine {stats['machine']}, "
          f"structured {stats['structured']}, overlong {stats['overlong']})")
    print(f"characters kept {kept_chars} of {raw_chars} "
          f"({100.0 * kept_chars / (raw_chars or 1):.1f}% of the raw user-message mass)")
    print()
    if args.script != "all":
        texts = ["".join(c for c in t if classify_script(c) == args.script) for t in texts]
        texts = [t for t in texts if t]

    report = build_report(texts)
    print(render_report(report, top=args.top))
    if args.out_dir:
        for path in write_frequency_files(report, args.out_dir):
            print(f"\nwrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
