#define MK_KINETIC_SPEED
#define MOUSEKEY_INTERVAL 10
#define MOUSEKEY_MOVE_DELTA 24
#define MOUSEKEY_INITIAL_SPEED 100
#define MOUSEKEY_BASE_SPEED 1000

#define MAX_DEFERRED_EXECUTORS 10

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX
#define UNICODE_TYPE_DELAY 0

#define SMTD_GLOBAL_TAP_TERM 200
#define SMTD_GLOBAL_RELEASE_TERM 30
#define SMTD_GLOBAL_FOLLOWING_TAP_TERM 400
#define SMTD_GLOBAL_SEQUENCE_TERM 300
